### ISSUE TITLE
Search Player Server

### ISSUE THREAD

**Issue by arves100** [GameProgressive/UniSpyServer#12]
The search player server (also known as GPSP) is responsable for checking profile information and searching the player in all the Users and Profiles informations.
This server is particularly relevant for GameSpy Arcade and similar applications.

Missing features:
- [x] Search if the unique nickname requested is really unique (Max 5 search with random numbers added in, \uniquesearch\)
- [x] Handling of check profile id (\check\)
- [x] Search other friends (\others\)
- [x] Creating of a new user (\newuser\)
- [x] Search for players that are playing (matchmaking?, \pmatch\)
- [x] Search a profile (\search\)
- [x] Any missing request not already discovered

**Comment by xiaojiuwo1993** [comment]
TODO: the key/value pairs in different request  are different, we have to implement multiple method to use the information in request to search a user in our database!

**Comment by arves100** [comment]
NOTE: Missing messaging system (bm, ...)
