### ISSUE TITLE
Connection Manager Server

### ISSUE THREAD

**Issue by arves100** [GameProgressive/UniSpyServer#9]
The Connection Manager Server (GPCM) is responsable for handling the login and the information of the profile.
The current GPCM server correctly logins, but several features are not implemented yet.

Missing features:
- [x] Restyling of the way that the Server saves the User information
- [x] Send friend list function (\bdy\)
- [x] Add products to the list of games (\inviteto\)
- [x] Complete user creation (\newuser\)
- [x] Ability to change email and password/User managment (\updateui\)
- [ ] Any possible command not yet discovered

**Comment by xiaojiuwo1993** [comment]
bm, getprofile,inviteto is not finished
